name: Demo Condicionales

on:
  push:

permissions: 
  contents: read

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: "Paso 1 - Siempre se ejecuta"
        run: echo "Paso 1 OK"
      - name: "Paso 2 - Forza un fallo (simulado)"
        run: exit 1
      - name: "Paso 3 - Sólo si todo es OK (se va a saltar)"
        if: success()
        run: echo "Este paso no se ejecutará porque el paso anterior fallo"
      - name: "Paso 4 - Sólo si hubo un fallo (si se ejecuta)"
        if: failure()
        run: echo "Fallo detectado - aqui iria una notificación."
      - name: "Paso 5 - Siempre corre (cleanup)"
        if: always()
        run: echo "Limpiez final, siempre se ejecuta()"
      - name: "Paso 6 - Sólo en rama main"
        if: github.ref_name == 'main'
        run: echo "Este paso sólo corre en main"
