name: Context demo

on:
  push:
  
  workflow_dispatch:

jobs:  
    build:
      name: "Context Demo JOB"    
      runs-on: ubuntu-latest
    
      steps:
        - name: "Contexto de Github"
          run: |
            echo "Repositorio: ${{github.repository}}"
            echo "Rama: ${{github.ref_name}}"
            echo "Commit SHA: ${{github.sha}}"
            echo "Actor: ${{github.actor}}"
            echo "Evento: ${{github.event_name}}"
