# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  workflow_dispatch:

jobs:
  solo-lectura:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: read
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Verificar que el checkout  funciono con solo read
        run: ls -lah
