name: Trigers Filters Demo

on:
  push:
    branches: [ "main", "release/**" ] #Cualquier rama que empiece con release
    paths:
      - "src/**"   #Solo si cambia dentro de src
      - "test/**"  #Solo si cambia dentro de test
  pull_request:
    branches:
      - main
      - release/**

permissions: 
  contents: read

jobs:
  build-filtrado:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Confirmar que el trigger paso los filtros
        run: |
          echo "Branch: ${{github.ref_name}}"
          echo "Evento: ${{github.event_name}}"
          echo "Commit: ${{github.sha}}"
